/**
 * RegistryManager — the ONLY write path to registry truth (§3): confirmed
 * proposals graduate to deployments.yaml via git. Policy (§5): direct commit
 * for version bumps; PR for structural changes (new customer, repo/ref shape).
 */
import type { GitHubConnector, ConnectorResult } from "../connectors/types.js";
import { ok, err } from "../connectors/types.js";
import type { RegistryEntry } from "../domain/types.js";
import { parseManifest, serializeManifest } from "./manifest.js";
import type { Registry } from "./registry.js";
import type { Proposal } from "./proposals.js";

export interface ApplyResult {
  mode: "commit" | "pr";
  url: string; // commit-ish branch URL or PR URL
}

export interface RegistryManagerDeps {
  github: GitHubConnector;
  registry: Registry;
  repo: string; // repo holding the manifest
  manifestPath: string;
  defaultBranch?: string; // default "main"
}

export class RegistryManager {
  private readonly branch: string;

  constructor(private readonly deps: RegistryManagerDeps) {
    this.branch = deps.defaultBranch ?? "main";
  }

  async apply(proposal: Proposal): Promise<ConnectorResult<ApplyResult>> {
    const { github, repo, manifestPath } = this.deps;

    const current = await github.readFile(repo, this.branch, manifestPath);
    if (!current.ok) return err(current.reason, `manifest read failed: ${current.detail}`);

    let entries: RegistryEntry[];
    try {
      entries = parseManifest(current.data);
    } catch (e) {
      return err("unavailable", `manifest parse failed: ${(e as Error).message}`);
    }

    if (proposal.kind === "version-bump") {
      const entry = entries.find((e) => e.customer === proposal.customer);
      if (!entry) return err("not-found", `customer "${proposal.customer}" not in manifest`);
      if (!proposal.change?.versionPin && !proposal.change?.ref) {
        return err("unavailable", "version-bump proposal has no change payload");
      }
      if (proposal.change.versionPin) {
        entry.versionPin = { value: proposal.change.versionPin, provenance: proposal.provenance };
      }
      if (proposal.change.ref) {
        entry.code.ref = { value: proposal.change.ref, provenance: proposal.provenance };
      }
      const message =
        `registry: ${proposal.customer} → ${proposal.change.versionPin ?? proposal.change.ref}` +
        `\n\nConfirmed proposal ${proposal.id}. Provenance: ${proposal.provenance[0]?.evidenceUrl ?? "n/a"}`;
      const push = await github.pushFiles(
        repo,
        this.branch,
        [{ path: manifestPath, content: serializeManifest(entries) }],
        message,
      );
      if (!push.ok) return err(push.reason, `manifest commit failed: ${push.detail}`);
      // Prime with what we just wrote — GitHub reads can lag behind the commit.
      this.deps.registry.prime(entries);
      return ok({ mode: "commit", url: `https://github.com/${repo}/blob/${this.branch}/${manifestPath}` });
    }

    // Structural change → PR.
    if (!proposal.entry) return err("unavailable", "new-customer proposal has no entry payload");
    const existing = entries.findIndex((e) => e.customer === proposal.customer);
    if (existing >= 0) entries[existing] = proposal.entry;
    else entries.push(proposal.entry);

    const branchName = `deploycontext/registry-${proposal.id}`;
    const created = await github.createBranch(repo, this.branch, branchName);
    if (!created.ok) return err(created.reason, `branch failed: ${created.detail}`);
    const push = await github.pushFiles(
      repo,
      branchName,
      [{ path: manifestPath, content: serializeManifest(entries) }],
      `registry: ${existing >= 0 ? "update" : "add"} ${proposal.customer}\n\nConfirmed proposal ${proposal.id}.`,
    );
    if (!push.ok) return err(push.reason, `push failed: ${push.detail}`);
    const pr = await github.openPr(repo, {
      base: this.branch,
      head: branchName,
      title: `registry: ${existing >= 0 ? "update" : "add"} ${proposal.customer}`,
      body:
        `Confirmed DeployContext proposal \`${proposal.id}\` (${proposal.kind}).\n\n` +
        `Provenance:\n${proposal.provenance.map((p) => `- ${p.source} · ${p.confidence} · ${p.evidenceUrl || "(no url)"}`).join("\n")}\n\n` +
        `_Generated by DeployContext._`,
    });
    if (!pr.ok) return err(pr.reason, `PR failed: ${pr.detail}`);
    // Note: cache refreshes when the PR merges; refresh now picks up main unchanged.
    return ok({ mode: "pr", url: pr.data.url });
  }
}
