/**
 * PR body — templated by the wrapper from the causal chain (§6):
 * bug report → customer + state → diagnosis with citations → repro test →
 * fix rationale (FIX_REPORT.md) → VerificationReport table → footer.
 * This is the product's face.
 */
import type { CodeFixBrief, Diagnosis, VerificationReport } from "../domain/types.js";
import { REPRO_TEST_PATH } from "./fixPrompt.js";

export interface PrContext {
  investigationId: string;
  customerDisplay?: string;
  triggerPermalink?: string;
  diagnosis?: Diagnosis;
}

const check = (v: boolean) => (v ? "✅" : "❌");

export function buildPrBody(args: {
  brief: CodeFixBrief;
  ctx: PrContext;
  verification: VerificationReport;
  fixReport: string | null;
}): string {
  const { brief, ctx, verification, fixReport } = args;

  const flags = Object.entries(brief.reproductionConditions.flags)
    .map(([k, v]) => `\`${k}=${String(v)}\``)
    .join(" · ");

  const evidence = brief.evidence
    .slice(0, 10)
    .map((e) => `- **${e.kind}** — ${e.summary}${e.source.evidenceUrl ? ` ([${e.source.source}](${e.source.evidenceUrl}))` : ` (${e.source.source})`}`)
    .join("\n");

  const sections = [
    `## Bug report`,
    ctx.triggerPermalink
      ? `Reported in Slack: ${ctx.triggerPermalink}`
      : `Reported via DeployContext investigation \`${ctx.investigationId}\`.`,
    ``,
    `## Customer & deployed state`,
    `**${ctx.customerDisplay ?? "Customer"}** runs \`${brief.repo}\` @ \`${brief.ref}\` (pinned).`,
    `${brief.reproductionConditions.versionNote}`,
    `Reproduces under: ${flags}`,
    brief.reproductionConditions.configExcerpt
      ? `\nConfig excerpt:\n\`\`\`\n${brief.reproductionConditions.configExcerpt}\n\`\`\``
      : ``,
    ``,
    `## Diagnosis`,
    ctx.diagnosis
      ? `**Verdict:** ${ctx.diagnosis.verdict} — ${ctx.diagnosis.culprit}\n\n${ctx.diagnosis.reasoning}`
      : brief.bugSummary,
    ``,
    `### Evidence`,
    evidence || "_none attached_",
    ``,
    `## Reproduction test`,
    `\`${REPRO_TEST_PATH}\` demonstrates the failure under the flag combination above; it fails on the original code and passes with this fix (verified independently by wrapper tooling, see below).`,
    ``,
    `## Fix rationale`,
    fixReport?.trim() || "_FIX_REPORT.md was not produced._",
    ``,
    `## Verification (computed by DeployContext tooling, not self-reported)`,
    `| Check | Result |`,
    `| --- | --- |`,
    `| Repro test added | ${check(verification.reproTestAdded)} |`,
    `| Repro test fails on original | ${check(verification.reproTestFailsOnOriginal)} |`,
    `| Repro test passes on fixed | ${check(verification.reproTestPassesOnFixed)} |`,
    `| Full suite passes | ${check(verification.fullSuitePassed)} |`,
    `| Lines changed (fix) | ${verification.linesChanged} |`,
    ``,
    `---`,
    `_Generated by [DeployContext](https://github.com/VikramIyer125/DeployContext) — investigation \`${ctx.investigationId}\`._`,
  ];

  return sections.filter((s) => s !== null).join("\n");
}
